---
- name: Install Docker
  hosts: all
  become: true

  tasks:
  - name: Set hostname
    hostname:
      name: dockerhost

  - name: Drop source package indexing
    lineinfile:
      state: absent
      regexp: "^deb-src"
      path: /etc/apt/sources.list

  - name: Install Docker and utilities
    apt:
      update_cache: true
      name:
      - curl
      - docker.io
      - nodejs
      - npm
    ignore_errors: "{{ ansible_check_mode }}"
