# Two-stage build to optimize image size

FROM maven:latest
WORKDIR /usr/src/project
ADD . .
RUN set -x && mvn clean install

FROM openjdk:14-jdk-alpine
EXPOSE 8080
WORKDIR /
COPY --from=0 /usr/src/project/target/docker-example-1.1.3.jar .
ENTRYPOINT ["/opt/openjdk-14/bin/java"]
CMD ["-jar", "docker-example-1.1.3.jar"]
